# Kernel Modules TO BE COPIED
PRODUCT_COPY_FILES += \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.usbmap:system/lib/modules/2.6.29-Kalim/modules.usbmap \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.alias:system/lib/modules/2.6.29-Kalim/modules.alias \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.symbols:system/lib/modules/2.6.29-Kalim/modules.symbols \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.isapnpmap:system/lib/modules/2.6.29-Kalim/modules.isapnpmap \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.ofmap:system/lib/modules/2.6.29-Kalim/modules.ofmap \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.ccwmap:system/lib/modules/2.6.29-Kalim/modules.ccwmap \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.pcimap:system/lib/modules/2.6.29-Kalim/modules.pcimap \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.ieee1394map:system/lib/modules/2.6.29-Kalim/modules.ieee1394map \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.seriomap:system/lib/modules/2.6.29-Kalim/modules.seriomap \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/net/ipv6/xfrm6_mode_ro.ko:system/lib/modules/2.6.29-Kalim/kernel/net/ipv6/xfrm6_mode_ro.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/net/ipv6/xfrm6_mode_tunnel.ko:system/lib/modules/2.6.29-Kalim/kernel/net/ipv6/xfrm6_mode_tunnel.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/net/ipv6/mip6.ko:system/lib/modules/2.6.29-Kalim/kernel/net/ipv6/mip6.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/net/ipv6/sit.ko:system/lib/modules/2.6.29-Kalim/kernel/net/ipv6/sit.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/net/ipv6/esp6.ko:system/lib/modules/2.6.29-Kalim/kernel/net/ipv6/esp6.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/net/ipv6/ip6_tunnel.ko:system/lib/modules/2.6.29-Kalim/kernel/net/ipv6/ip6_tunnel.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/net/ipv6/xfrm6_mode_transport.ko:system/lib/modules/2.6.29-Kalim/kernel/net/ipv6/xfrm6_mode_transport.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/net/ipv6/xfrm6_tunnel.ko:system/lib/modules/2.6.29-Kalim/kernel/net/ipv6/xfrm6_tunnel.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/net/ipv6/ipcomp6.ko:system/lib/modules/2.6.29-Kalim/kernel/net/ipv6/ipcomp6.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/net/ipv6/ipv6.ko:system/lib/modules/2.6.29-Kalim/kernel/net/ipv6/ipv6.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/net/ipv6/ah6.ko:system/lib/modules/2.6.29-Kalim/kernel/net/ipv6/ah6.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/net/ipv6/tunnel6.ko:system/lib/modules/2.6.29-Kalim/kernel/net/ipv6/tunnel6.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/net/ipv6/xfrm6_mode_beet.ko:system/lib/modules/2.6.29-Kalim/kernel/net/ipv6/xfrm6_mode_beet.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/net/netfilter/xt_TCPMSS.ko:system/lib/modules/2.6.29-Kalim/kernel/net/netfilter/xt_TCPMSS.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/net/xfrm/xfrm_ipcomp.ko:system/lib/modules/2.6.29-Kalim/kernel/net/xfrm/xfrm_ipcomp.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/net/ipv4/tunnel4.ko:system/lib/modules/2.6.29-Kalim/kernel/net/ipv4/tunnel4.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/drivers/staging/ramzswap/ramzswap.ko:system/lib/modules/2.6.29-Kalim/kernel/drivers/staging/ramzswap/ramzswap.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/drivers/hid/hid-dummy.ko:system/lib/modules/2.6.29-Kalim/kernel/drivers/hid/hid-dummy.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/fs/ext4/ext4.ko:system/lib/modules/2.6.29-Kalim/kernel/fs/ext4/ext4.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/fs/jbd2/jbd2.ko:system/lib/modules/2.6.29-Kalim/kernel/fs/jbd2/jbd2.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/crypto/deflate.ko:system/lib/modules/2.6.29-Kalim/kernel/crypto/deflate.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/kernel/lib/crc16.ko:system/lib/modules/2.6.29-Kalim/kernel/lib/crc16.ko \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.order:system/lib/modules/2.6.29-Kalim/modules.order \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.devname:system/lib/modules/2.6.29-Kalim/modules.devname \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.alias.bin:system/lib/modules/2.6.29-Kalim/modules.alias.bin \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.symbols.bin:system/lib/modules/2.6.29-Kalim/modules.symbols.bin \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.inputmap:system/lib/modules/2.6.29-Kalim/modules.inputmap \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.dep:system/lib/modules/2.6.29-Kalim/modules.dep \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.dep.bin:system/lib/modules/2.6.29-Kalim/modules.dep.bin \
    device/htc/tattoo/custom/modules/2.6.29-Kalim/modules.softdep:system/lib/modules/2.6.29-Kalim/modules.softdep \
    device/htc/tattoo/custom/modules/wlan.ko:system/lib/modules/wlan.ko
