#!/system/bin/sh

SETTINGSDB=/data/data/com.android.providers.settings/databases/settings.db
if [ ! -f $SETTINGSDB ] ;
then
  exit
fi

CALIBRATION=`sqlite3 $SETTINGSDB "select value from system where name='calibration_points';"`
if [ ! -z $CALIBRATION ] ;
then
  echo $CALIBRATION > /sys/class/input/input1/calibration_points
fi

