#!/system/bin/sh

# - SquashFS mounted.
setprop fy.modules.mounted 0

if [ -f /system/squashfs/modules.sqf ]
then
    busybox losetup /dev/block/loop0 /system/squashfs/modules.sqf
    busybox mount -o ro -t squashfs /dev/block/loop0 /system/lib/modules
    setprop fy.modules.mounted 1
fi

exit 0
