#!/system/bin/sh
L="log -p i -t cm"
$L "Kalim iniciado userinit";

# - run customized shell at boot time
userscript="/data/local/bin/autostart.sh"

[ -x $userscript ] && /system/bin/sh $userscript

exit 0
